// Google Calendar API utilities

const SCOPES = "https://www.googleapis.com/auth/calendar.events";
const DISCOVERY_DOC = "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest";

let tokenClient: google.accounts.oauth2.TokenClient | null = null;
let gapiInited = false;
let gisInited = false;
let currentClientId = "";
let currentApiKey = "";

/**
 * Initialize GAPI (Google API client)
 */
export async function initializeGapi(apiKey: string): Promise<void> {
  return new Promise((resolve, reject) => {
    gapi.load("client", async () => {
      try {
        await gapi.client.init({
          apiKey: apiKey,
          discoveryDocs: [DISCOVERY_DOC],
        });
        gapiInited = true;
        currentApiKey = apiKey;
        resolve();
      } catch (error) {
        reject(error);
      }
    });
  });
}

/**
 * Initialize Google Identity Services (for OAuth)
 */
export function initializeGis(clientId: string, callback: () => void): void {
  tokenClient = google.accounts.oauth2.initTokenClient({
    client_id: clientId,
    scope: SCOPES,
    callback: callback,
  });
  gisInited = true;
  currentClientId = clientId;
}

/**
 * Initialize both GAPI and GIS (convenience function)
 */
export async function initGoogleApi(clientId: string, apiKey: string): Promise<void> {
  currentClientId = clientId;
  currentApiKey = apiKey;
  
  // Initialize GAPI
  await initializeGapi(apiKey);
  
  // Initialize GIS
  return new Promise((resolve) => {
    initializeGis(clientId, () => {
      resolve();
    });
  });
}

/**
 * Sign in to Google Calendar
 */
export async function signIn(): Promise<void> {
  if (!gapiInited || !gisInited) {
    if (currentClientId && currentApiKey) {
      await initGoogleApi(currentClientId, currentApiKey);
    } else {
      throw new Error("Google API not initialized. Please configure Client ID and API Key first.");
    }
  }
  
  return new Promise((resolve, reject) => {
    try {
      requestAccessToken();
      // Wait a bit for the token to be set
      const checkToken = setInterval(() => {
        if (isSignedIn()) {
          clearInterval(checkToken);
          resolve();
        }
      }, 500);
      
      // Timeout after 30 seconds
      setTimeout(() => {
        clearInterval(checkToken);
        if (!isSignedIn()) {
          reject(new Error("Sign in timeout"));
        }
      }, 30000);
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Sign out from Google Calendar
 */
export function signOut(): void {
  revokeAccessToken();
}

/**
 * Request OAuth token
 */
export function requestAccessToken(): void {
  if (!tokenClient) {
    throw new Error("Token client not initialized");
  }
  
  // Check if there's already a token
  if (gapi.client.getToken() === null) {
    // Prompt the user to select a Google Account and ask for consent
    tokenClient.requestAccessToken({ prompt: "consent" });
  } else {
    // Skip display of account chooser and consent dialog for an existing session
    tokenClient.requestAccessToken({ prompt: "" });
  }
}

/**
 * Revoke OAuth token
 */
export function revokeAccessToken(): void {
  const token = gapi.client.getToken();
  if (token !== null) {
    google.accounts.oauth2.revoke(token.access_token, () => {
      gapi.client.setToken(null);
    });
  }
}

/**
 * Check if user is signed in
 */
export function isSignedIn(): boolean {
  try {
    if (typeof gapi === 'undefined' || !gapi.client) {
      return false;
    }
    return gapi.client.getToken() !== null;
  } catch (error) {
    return false;
  }
}

/**
 * Create a calendar event with nutrition data
 */
export async function createCalendarEvent(
  date: Date,
  calorieCount: number,
  macros: { fat: number; carbs: number; protein: number },
  notes?: string
): Promise<any> {
  const startDate = new Date(date);
  startDate.setHours(0, 0, 0, 0);
  
  const endDate = new Date(date);
  endDate.setHours(23, 59, 59, 999);

  const event = {
    summary: `Daily Nutrition - ${calorieCount} calories`,
    description: `
📊 Daily Nutrition Summary

Total Calories: ${calorieCount}

Macronutrients:
• Fat: ${macros.fat}g
• Carbs: ${macros.carbs}g
• Protein: ${macros.protein}g

${notes ? `Notes:\n${notes}` : ""}

Generated by NutriTrack
    `.trim(),
    start: {
      dateTime: startDate.toISOString(),
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    end: {
      dateTime: endDate.toISOString(),
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    colorId: "9", // Blue color
  };

  try {
    const response = await gapi.client.calendar.events.insert({
      calendarId: "primary",
      resource: event,
    });
    return response.result;
  } catch (error) {
    console.error("Error creating calendar event:", error);
    throw error;
  }
}

/**
 * Get events for a specific date
 */
export async function getEventsForDate(date: Date): Promise<any[]> {
  const startDate = new Date(date);
  startDate.setHours(0, 0, 0, 0);
  
  const endDate = new Date(date);
  endDate.setHours(23, 59, 59, 999);

  try {
    const response = await gapi.client.calendar.events.list({
      calendarId: "primary",
      timeMin: startDate.toISOString(),
      timeMax: endDate.toISOString(),
      showDeleted: false,
      singleEvents: true,
      orderBy: "startTime",
    });
    return response.result.items || [];
  } catch (error) {
    console.error("Error fetching calendar events:", error);
    throw error;
  }
}

/**
 * Update an existing calendar event
 */
export async function updateCalendarEvent(
  eventId: string,
  calorieCount: number,
  macros: { fat: number; carbs: number; protein: number },
  notes?: string
): Promise<any> {
  const event = {
    summary: `Daily Nutrition - ${calorieCount} calories`,
    description: `
📊 Daily Nutrition Summary

Total Calories: ${calorieCount}

Macronutrients:
• Fat: ${macros.fat}g
• Carbs: ${macros.carbs}g
• Protein: ${macros.protein}g

${notes ? `Notes:\n${notes}` : ""}

Generated by NutriTrack
    `.trim(),
  };

  try {
    const response = await gapi.client.calendar.events.patch({
      calendarId: "primary",
      eventId: eventId,
      resource: event,
    });
    return response.result;
  } catch (error) {
    console.error("Error updating calendar event:", error);
    throw error;
  }
}

export function isInitialized(): boolean {
  return gapiInited && gisInited;
}